"""Test the autogenerated openapi"""
import logging

from fastapi.testclient import TestClient

LOGGER = logging.getLogger(__name__)


def test_get_openapi(mtlsclient: TestClient) -> None:
    """Check that getting openapi.json works"""
    resp = mtlsclient.get("/api/openapi.json")
    assert resp.status_code == 200


def test_get_openapi_docs(mtlsclient: TestClient) -> None:
    """Check that getting openapi.json works"""
    resp = mtlsclient.get("/api/docs")
    assert resp.status_code == 200
