<?xml version='1.0' standalone='yes'?>
<preferences>
  <preference version='1' name='com.atakmap.app_preferences'>
    <!--Network mesh key, generated by takrmapi -->
    <entry key='networkMeshKey' class='class java.lang.String'>{{ v.tak_network_mesh_key }}</entry>
  </preference>
</preferences>
