<?xml version='1.0' standalone='yes'?>
<preferences>
  <preference version='1' name='com.atakmap.app_preferences'>
    <!-- Example of network mesh key, generated by atak -->
    <entry key='networkMeshKey' class='class java.lang.String'>{{ tak_network_mesh_key }}</entry>
  </preference>
</preferences>
