on:
    pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: Build test image
        run: |
          docker build --target test -t takrmapi:test .
      - name: run test image
        run: |
         docker run --rm -v `pwd`":/app" takrmapi:test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/pytest*.xml'
          detailed_summary: true
          check_name: 'JUnit report (local)'

  devel_shell:
    runs-on: ubuntu-latest
    steps:
    - uses: pvarki/ci@main
      with:
        dockerfile-target: devel_shell
        image-tag: takrmapi:devel_shell
