on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

# Remember to change TAK_RELEASE also in pull_request.yml
env:
  TAK_RELEASE: 5.8-RELEASE-69

jobs:
  snyk-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pvarki/config-ci-library/.github/actions/setup-python@main
      - uses: pvarki/config-ci-library/.github/actions/snyk-monitor@main
        with:
          snyk-org: deployapp-products
          snyk-token: ${{ secrets.SNYK_TOKEN }}

  publish:
    name: Publish Docker image
    runs-on: arc-runner-set
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Publish Docker image
        uses: pvarki/config-ci-library/.github/actions/publish-image@main
        with:
          product: tak
          component: integration
          extra-tag: tak${{ env.TAK_RELEASE }}
          build-args: |
            TAKSERVER_IMAGE=ghcr.io/pvarki/tak-server:${{ env.TAK_RELEASE }}
          dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          acr-repo: ${{ vars.ACR_REPO }}
          acr-username: ${{ vars.ACR_USERNAME }}
          acr-token: ${{ secrets.ACR_TOKEN }}

  release:
    name: Tag and release
    needs: publish
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    permissions:
      contents: write
      packages: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: pvarki/config-ci-library/.github/actions/tag-release@main
        id: tag
      - uses: pvarki/config-ci-library/.github/actions/release-notes@main
        if: steps.tag.outputs.tag != ''
        with:
          ref: ${{ steps.tag.outputs.tag }}
          release: ${{ steps.tag.outputs.version }}
          product: tak-integration
          attach-to-release: "true"

  # OpenAPI spec to releases.
  openapi:
    name: Attach OpenAPI spec
    needs: release
    if: needs.release.outputs.tag != ''
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ needs.release.outputs.tag }}
      - uses: pvarki/config-ci-library/.github/actions/setup-python@main
        with:
          python-version: "3.11"
      - name: Generate and attach OpenAPI spec
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          uv run takrmapi openapi > openapi.json
          gh release upload "${{ needs.release.outputs.tag }}" openapi.json --clobber
