on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  snyk-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pvarki/config-ci-library/.github/actions/setup-python@main
      - uses: pvarki/config-ci-library/.github/actions/snyk-monitor@main
        with:
          snyk-org: deployapp-products
          snyk-token: ${{ secrets.SNYK_TOKEN }}

  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Publish Docker image
        uses: pvarki/config-ci-library/.github/actions/publish-image@main
        with:
          product: tak
          component: integration
          platforms: linux/amd64
          dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          acr-repo: ${{ vars.ACR_REPO }}
          acr-username: ${{ vars.ACR_USERNAME }}
          acr-token: ${{ secrets.ACR_TOKEN }}
